### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Icahpv** [sait-wbdv/helpdesk#3]
Github pull request after License creation. I made my repo folder first and started my vscode before I did my license. 

- Says I'm 1 commit away from 2 commits for this branch. 
- Creation of license created a license branch.

**Comment by lilyx13** [comment]
Were you able to merge the pull request into main? I believe in that case it's the gui's process for merging your git commits.

**Comment by Icahpv** [comment]
**Solved the problem!** Make sure to _"Commit directly to the main branch"_ instead of creating a new branch at the bottom of choosing a template for the license page.

**Comment by lilyx13** [comment]
Nice! That's a really good tip for anyone else that hits that issue in the future. Good fix.
